/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CryptoRouteImport } from './routes/crypto'
import { Route as IndexDothtmlRouteImport } from './routes/index[.]html'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as StocksRouteImport } from './routes/stocks'
import { Route as AuthenticatedPortfolioRouteImport } from './routes/_authenticated/portfolio'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CryptoRoute = CryptoRouteImport.update({
  id: '/crypto',
  path: '/crypto',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexDothtmlRoute = IndexDothtmlRouteImport.update({
  id: '/index.html',
  path: '/index.html',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const StocksRoute = StocksRouteImport.update({
  id: '/stocks',
  path: '/stocks',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPortfolioRoute = AuthenticatedPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/crypto': typeof CryptoRoute
  '/index.html': typeof IndexDothtmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stocks': typeof StocksRoute
  '/portfolio': typeof AuthenticatedPortfolioRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/crypto': typeof CryptoRoute
  '/index.html': typeof IndexDothtmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stocks': typeof StocksRoute
  '/portfolio': typeof AuthenticatedPortfolioRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/crypto': typeof CryptoRoute
  '/index.html': typeof IndexDothtmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stocks': typeof StocksRoute
  '/_authenticated/portfolio': typeof AuthenticatedPortfolioRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/crypto'
    | '/index.html'
    | '/sitemap.xml'
    | '/stocks'
    | '/portfolio'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/crypto'
    | '/index.html'
    | '/sitemap.xml'
    | '/stocks'
    | '/portfolio'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/crypto'
    | '/index.html'
    | '/sitemap.xml'
    | '/stocks'
    | '/_authenticated/portfolio'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CryptoRoute: typeof CryptoRoute
  IndexDothtmlRoute: typeof IndexDothtmlRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StocksRoute: typeof StocksRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crypto': {
      id: '/crypto'
      path: '/crypto'
      fullPath: '/crypto'
      preLoaderRoute: typeof CryptoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/index.html': {
      id: '/index.html'
      path: '/index.html'
      fullPath: '/index.html'
      preLoaderRoute: typeof IndexDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stocks': {
      id: '/stocks'
      path: '/stocks'
      fullPath: '/stocks'
      preLoaderRoute: typeof StocksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/portfolio': {
      id: '/_authenticated/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof AuthenticatedPortfolioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedPortfolioRoute: typeof AuthenticatedPortfolioRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedPortfolioRoute: AuthenticatedPortfolioRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CryptoRoute: CryptoRoute,
  IndexDothtmlRoute: IndexDothtmlRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StocksRoute: StocksRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
